---
- name: Configure Service | Template systemd unit
  become: true
  ansible.builtin.template:
    src: vector.service.j2
    dest: /etc/systemd/system/vector.service
    mode: "0644"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
  notify: restart vector service


  # - name: Enable vector service
  # become: true
  # ansible.builtin.service:
  #   name: vector
  #   state: restarted
  # when: ansible_facts['virtualization_type'] != 'docker'